export const CONSTANTS = {
  COUPONS_NUMBER: 10,
  SEQUENCIAL_GENERATION: 100,
  RANDOM_GENERATION: 101,
  COUPON_LENGTH: 8,
  COUPON_PAD: "0"
}

export const COUPON_GENERATION = CONSTANTS.RANDOM_GENERATION
